
= Rxvertx-college

=== About this application

This application is a basic implementation of Reactive Vertx. This application has basic supporting CRUD operation. It uses event bus to communicate between Verticles. 

This application uses Redis database.To run this application successfully please make sure Redis DB is running on default port 6379.


=== Curl commands to use the REST API's

* **INSERT Student**


	Successful insertion operation will provide a student id in response. This student id can be used for further operations.



		```
		curl --request POST \
		  --url http://localhost:8080/students \
		  --header 'content-type: application/json' \
		  --data '{
			"docType": "STUDENT",
			"name": "Robert Parker",
			"phoneNumber": 17922599889,
			"DepartmentName": "CIVIL_ENGINEERING"
		}'
		```


* **GET Student**

		```
		curl --request GET \
		  --url http://localhost:8080/students/{studentId}
		```



* **UPDATE Student**

		```
		curl --request PUT \
		  --url http://localhost:8080/students/{studentId} \
		  --header 'content-type: application/json' \
		  --data '{
		  "docType": "STUDENT",
		  "name": "Robe Wallas",
		  "phoneNumber": 17922599889,
		  "DepartmentName": "MATHES",
		}'

		```

* **DELETE Student**

		```
		curl --request DELETE \
		  --url http://localhost:8080/students/{studentId}
		```

=== Possible values for DepartmentName

	```
	 COMPUTER_SCIENCE
	 ELECTRIC_ENGINEERING
	 MECHANICAL_ENGINEERING
	 CIVIL_ENGINEERING
	 MATHES

	```












image:https://img.shields.io/badge/vert.x-3.9.2-purple.svg[link="https://vertx.io"]

This application was generated using http://start.vertx.io

== Building

To launch your tests:
```
./gradlew clean test
```

To package your application:
```
./gradlew clean assemble
```

To run your application:
```
./gradlew clean run
```

== Help

* https://vertx.io/docs/[Vert.x Documentation]
* https://stackoverflow.com/questions/tagged/vert.x?sort=newest&pageSize=15[Vert.x Stack Overflow]
* https://groups.google.com/forum/?fromgroups#!forum/vertx[Vert.x User Group]
* https://gitter.im/eclipse-vertx/vertx-users[Vert.x Gitter]

